monitor.alsa.rules = [
  {
    matches = [
      {
        device.name = "~alsa_card.usb-4K_USB_Camera_4K_USB_Camera_01.00.00-.*"
      }
    ]
    actions = {
      update-props = {
        device.disabled = true
      }
    }
  }
]
